# Generated by Django 5.2.5 on 2025-08-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingId', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Awaiting Payment', max_length=100)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('expectedDate', models.DateField(blank=True, null=True)),
                ('progressPercent', models.IntegerField(default=10)),
                ('progressLabels', models.JSONField(default=list)),
                ('requiresPayment', models.BooleanField(default=True)),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recentEvent', models.JSONField(blank=True, null=True)),
                ('allEvents', models.JSONField(blank=True, null=True)),
                ('shipmentDetails', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholderName', models.CharField(max_length=255)),
                ('billingAddress', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.shipment')),
            ],
        ),
    ]
