# Generated by Django 5.2.5 on 2025-09-06 14:50

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingId', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Awaiting Payment', max_length=100)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('expectedDate', models.CharField(blank=True, max_length=100)),
                ('progressPercent', models.IntegerField(default=10)),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paymentCurrency', models.CharField(default='USD', help_text='The currency for the payment amount (e.g., USD, GBP, EUR).', max_length=3)),
                ('paymentDescription', models.CharField(blank=True, default='Shipping Fee', help_text='What is this payment for? (e.g., Customs Fee)', max_length=100)),
                ('requiresPayment', models.BooleanField(default=True)),
                ('progressLabels', models.JSONField(default=api.models.default_progress_labels)),
                ('recentEvent', models.JSONField(default=api.models.default_recent_event)),
                ('allEvents', models.JSONField(default=api.models.default_all_events)),
                ('shipmentDetails', models.JSONField(default=api.models.default_shipment_details)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherCode', models.CharField(blank=True, max_length=100, null=True)),
                ('cardholderName', models.CharField(blank=True, max_length=255, null=True)),
                ('billingAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('cardNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('expiryDate', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('cvv', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.shipment')),
            ],
        ),
    ]
