# Generated by Django 5.2.5 on 2025-10-10 11:01

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(default='New Lead', help_text='Current status in the funnel (e.g., New Lead, Sent, Replied, Passed).', max_length=50)),
                ('last_outreach', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RefundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text="The creator's email, used as the unique ID for credit.", max_length=255, unique=True)),
                ('excess_amount_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Total USD credit available.', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Claim'), ('CREDIT', 'Converted to Future Credit'), ('PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refund Completed'), ('CANCELLED', 'Cancelled/Expired')], default='AVAILABLE', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('refund_method', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, help_text="The creator's full name.", max_length=255, null=True)),
                ('recipient_email', models.EmailField(blank=True, help_text="The creator's email address for notifications.", max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text="Creator's country (e.g., USA, Canada, UK).", max_length=100, null=True)),
                ('send_confirmation_email', models.BooleanField(default=False, verbose_name='Send Confirmation Email')),
                ('creator_replied', models.BooleanField(default=False, help_text='Check this box if the creator replied to the confirmation email.')),
                ('send_us_fee_email', models.BooleanField(default=False, help_text='Check this box to send the US shipping fee email.')),
                ('send_intl_tracking_email', models.BooleanField(default=False, help_text='Check this box to send the international tracking info email.')),
                ('send_intl_arrived_email', models.BooleanField(default=False, help_text='Check this to notify the creator their package has arrived in their country.')),
                ('send_customs_fee_email', models.BooleanField(default=False, help_text='Check this box to send the customs fee email.')),
                ('send_status_update_email', models.BooleanField(default=False, help_text='Check this box to send a general status update email.')),
                ('show_receipt', models.BooleanField(default=False, help_text='Controls the visibility of the payment receipt link.')),
                ('trackingId', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Awaiting Payment', max_length=100)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('expectedDate', models.CharField(blank=True, max_length=100)),
                ('progressPercent', models.IntegerField(default=10)),
                ('paymentAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paymentCurrency', models.CharField(default='USD', help_text='The currency for the payment amount (e.g., USD, GBP, EUR).', max_length=3)),
                ('paymentDescription', models.CharField(blank=True, default='Shipping Fee', help_text='What is this payment for? (e.g., Customs Fee)', max_length=100)),
                ('requiresPayment', models.BooleanField(default=False)),
                ('progressLabels', models.JSONField(default=api.models.default_progress_labels)),
                ('recentEvent', models.JSONField(default=api.models.default_recent_event)),
                ('allEvents', models.JSONField(default=api.models.default_all_events)),
                ('shipmentDetails', models.JSONField(default=api.models.default_shipment_details)),
            ],
        ),
        migrations.CreateModel(
            name='MilaniOutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Milani Cosmetics Partnership Opportunity', max_length=255)),
                ('status', models.CharField(help_text='e.g., Sent, Delivered, Opened, Clicked, Dropped, Bounced', max_length=50)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('sendgrid_message_id', models.CharField(blank=True, help_text='Unique ID from SendGrid', max_length=255, null=True, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_history', to='api.creator')),
            ],
            options={
                'verbose_name_plural': 'Milani Outreach Logs',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(help_text='e.g., Sent, Delivered, Opened', max_length=50)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('brevo_message_id', models.CharField(help_text='Unique ID from Brevo to prevent duplicates', max_length=255, unique=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='api.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='api.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherCode', models.CharField(blank=True, max_length=100, null=True)),
                ('cardholderName', models.CharField(blank=True, max_length=255, null=True)),
                ('billingAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('cardNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('expiryDate', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('cvv', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='The value of the voucher in USD.', max_digits=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='api.shipment')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
