# Generated by Django 5.2.5 on 2025-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiryDate',
            field=models.CharField(default='', max_length=7),
        ),
    ]
