# Generated by Django 5.2.5 on 2025-10-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_customs_fee_reminder_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending Payment', max_length=100),
        ),
    ]
