# Generated by Django 5.2.5 on 2025-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text="The creator's email address for notifications.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_name',
            field=models.CharField(blank=True, help_text="The creator's full name.", max_length=255, null=True),
        ),
    ]
