# Generated by Django 5.2.5 on 2025-08-24 16:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_cardnumber_payment_cvv_payment_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='allEvents',
            field=models.JSONField(default=api.models.default_all_events),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='progressLabels',
            field=models.JSONField(default=api.models.default_progress_labels),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recentEvent',
            field=models.JSONField(default=api.models.default_recent_event),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentDetails',
            field=models.JSONField(default=api.models.default_shipment_details),
        ),
    ]
