# Generated by Django 5.2.5 on 2025-10-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shipment_send_customs_fee_reminder_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemail',
            name='brevo_message_id',
        ),
        migrations.AddField(
            model_name='sentemail',
            name='provider_message_id',
            field=models.CharField(default='legacy_id', help_text='Unique ID from the email provider (e.g., MailerSend, SendGrid)', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
