# Generated by Django 5.2.5 on 2025-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shipment_recipient_email_shipment_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='country',
            field=models.CharField(blank=True, help_text="Creator's country (e.g., USA, Canada, UK).", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_customs_fee_email',
            field=models.BooleanField(default=False, help_text='Check this box to send the customs fee email.'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_intl_tracking_email',
            field=models.BooleanField(default=False, help_text='Check this box to send the international tracking info email.'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_us_fee_email',
            field=models.BooleanField(default=False, help_text='Check this box to send the US shipping fee email.'),
        ),
    ]
