# Generated by Django 5.2.5 on 2025-08-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shipment_allevents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='voucherCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billingAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholderName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiryDate',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
