# Generated by Django 5.2.5 on 2025-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipment_country_shipment_send_customs_fee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='creator_replied',
            field=models.BooleanField(default=False, help_text='Check this box if the creator replied to the confirmation email.'),
        ),
    ]
