# Generated by Django 5.2.5 on 2025-12-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sentemail_brevo_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='manual_email_body',
            field=models.TextField(blank=True, help_text='Custom message content'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manual_email_heading',
            field=models.CharField(blank=True, help_text='Bold title', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manual_email_subject',
            field=models.CharField(blank=True, help_text='Subject line', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trigger_manual_email',
            field=models.BooleanField(default=False, verbose_name='SEND MANUAL EMAIL NOW'),
        ),
    ]
