# Generated by Django 5.2.5 on 2025-09-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shipment_creator_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(help_text='e.g., Sent, Delivered, Opened', max_length=50)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('brevo_message_id', models.CharField(help_text='Unique ID from Brevo to prevent duplicates', max_length=255, unique=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='api.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
    ]
