# Generated by Django 5.2.5 on 2025-12-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shipment_manual_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='manual_email_button_text',
            field=models.CharField(blank=True, default='Finalize Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manual_email_include_payment_button',
            field=models.BooleanField(default=False, verbose_name='Include Payment Button'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manual_email_include_tracking_box',
            field=models.BooleanField(default=False, verbose_name='Include Tracking Box'),
        ),
    ]
