# Generated by Django 5.2.5 on 2025-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment_vouchercode_alter_payment_billingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='expectedDate',
            field=models.CharField(blank=True, default='TBD', max_length=100),
            preserve_default=False,
        ),
    ]
