# Generated by Django 5.2.5 on 2025-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_status_update_email',
            field=models.BooleanField(default=False, help_text='Check this box to send a general status update email.'),
        ),
    ]
