# Generated by Django 5.2.5 on 2026-02-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shipment_shieldclimb_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_address_in',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_ipn_token',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_payment_status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_polygon_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_txid_in',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_txid_out',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shieldclimb_value_received',
        ),
    ]
