# Generated by Django 5.2.5 on 2026-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_shipment_shieldclimb_address_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_provider', models.CharField(choices=[('mailersend', 'MailerSend'), ('resend', 'Resend')], default='resend', help_text='The active email provider. Change this to switch providers instantly.', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
