# Generated by Django 5.2.5 on 2025-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_receipt_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='show_receipt',
            field=models.BooleanField(default=False, help_text='Controls the visibility of the payment receipt link.'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='requiresPayment',
            field=models.BooleanField(default=False),
        ),
    ]
