# Generated by Django 5.2.5 on 2026-02-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Package Received', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='trackingId',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_provider',
            field=models.CharField(choices=[('mailersend', 'MailerSend'), ('resend', 'Resend'), ('sendgrid', 'SendGrid')], default='mailersend', help_text='The active email provider. Change this to switch providers instantly.', max_length=20),
        ),
    ]
