# Generated by Django 5.2.5 on 2025-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shipment_show_receipt_alter_shipment_requirespayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_intl_arrived_email',
            field=models.BooleanField(default=False, help_text='Check this to notify the creator their package has arrived in their country.'),
        ),
    ]
