# Generated by Django 5.2.5 on 2026-02-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_shipment_status_alter_shipment_trackingid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('auto', 'Auto — Gemini 2.5 Flash → Gemini 2.0 Flash Lite → Local'), ('local_only', 'Local Only — No API calls (unlimited, instant)')], default='auto', help_text='Controls AI engine for shipment generation. Auto tries Gemini first, falls back to local if rate limited.', max_length=20),
        ),
    ]
