# Generated by Django 5.2.5 on 2025-09-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shipment_send_intl_arrived_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, verbose_name='Send Confirmation Email'),
        ),
    ]
