# Generated by Django 5.2.5 on 2025-10-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shipment_send_intl_arrived_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(default='New Lead', help_text='Current status in the funnel (e.g., New Lead, Sent, Replied, Passed).', max_length=50)),
                ('last_outreach', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MilaniOutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Milani Cosmetics Partnership Opportunity', max_length=255)),
                ('status', models.CharField(help_text='e.g., Sent, Delivered, Opened, Clicked, Dropped, Bounced', max_length=50)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('sendgrid_message_id', models.CharField(blank=True, help_text='Unique ID from SendGrid', max_length=255, null=True, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_history', to='api.creator')),
            ],
            options={
                'verbose_name_plural': 'Milani Outreach Logs',
                'ordering': ['-event_time'],
            },
        ),
    ]
