# Generated by Django 5.2.5 on 2025-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_creator_milanioutreachlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, verbose_name='Send Confirmation Email'),
        ),
    ]
