# Generated by Django 5.2.5 on 2026-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sitesettings_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_stage_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_stage_key',
            field=models.CharField(blank=True, default='label_created', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
