# Generated by Django 5.2.5 on 2025-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shipment_send_confirmation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text="The creator's email, used as the unique ID for credit.", max_length=255, unique=True)),
                ('excess_amount_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Total USD credit available.', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Claim'), ('CREDIT', 'Converted to Future Credit'), ('PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refund Completed'), ('CANCELLED', 'Cancelled/Expired')], default='AVAILABLE', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('refund_method', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
    ]
