# Generated by Django 5.2.5 on 2026-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shipment_current_stage_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='allowed_payment_providers',
            field=models.JSONField(blank=True, default=list, help_text='Leave empty for automatic ShieldClimb provider selection. Check specific providers in admin to override.'),
        ),
    ]
