# Generated by Django 5.2.5 on 2025-10-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_refundbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.shipment'),
        ),
    ]
