# Generated by Django 5.2.5 on 2026-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shipment_allowed_payment_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='provider_display_order',
            field=models.CharField(blank=True, default='', help_text='Full ordered list, comma-separated. Example: robinhood,stripe,transak — overrides auto providers completely. Leave empty to use auto + extras above.', max_length=500),
        ),
    ]
