# Generated by Django 5.2.5 on 2026-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shipment_provider_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='paymentDescription',
            field=models.CharField(blank=True, default='Import Duties', help_text='What is this payment for? (e.g., Import Duties, Customs Fee)', max_length=100),
        ),
    ]
