# Generated by Django 5.2.5 on 2025-10-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_payment_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='value_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The value of the voucher in USD.', max_digits=10),
        ),
    ]
