# Generated by Django 5.2.5 on 2026-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_shipment_paymentdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='paymentDescription',
            field=models.CharField(blank=True, default='Shipping Fee', help_text='What is this payment for? (e.g., Customs Fee)', max_length=100),
        ),
    ]
