# Generated by Django 5.2.5 on 2026-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_shipment_paymentdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_us_redelivery_reminder_email',
            field=models.BooleanField(default=False, help_text='Send redelivery fee reminder for domestic shipments.'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_us_tracking_email',
            field=models.BooleanField(default=False, help_text='Send domestic tracking notification — package is on its way.'),
        ),
    ]
