# Generated by Django 5.2.5 on 2026-03-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shipment_send_us_redelivery_reminder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='paymentActionMessage',
            field=models.CharField(blank=True, default='', help_text='Custom message for the ⚠ Action Required bar on the tracking page. Leave blank for smart default.', max_length=500),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='paymentDescription',
            field=models.CharField(blank=True, default='Import Duties', help_text='What is this payment for? (e.g., Import Duties, Redelivery Fee) — shows next to the amount.', max_length=100),
        ),
    ]
