# Generated by Django 5.2.5 on 2026-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shipment_paymentactionmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_intl_redelivery_reminder_email',
            field=models.BooleanField(default=False, help_text='Send redelivery fee reminder for international shipments.'),
        ),
    ]
