# Generated by Django 5.2.5 on 2026-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shipment_send_intl_redelivery_reminder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_image_url',
            field=models.URLField(blank=True, default='', help_text='URL of generated proof of delivery image.', max_length=500),
        ),
    ]
