# Generated by Django 5.2.5 on 2026-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shipment_delivery_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_customs_fee_final_email',
            field=models.BooleanField(default=False, help_text='Final notice — package will be returned in 72 hours if unpaid.'),
        ),
    ]
