# Generated by Django 5.2.5 on 2026-04-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shipment_send_customs_fee_final_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='send_intl_first_notification',
            field=models.BooleanField(default=False, help_text='First email — international. Carrier-style shipment notification. Use instead of confirmation email.'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_us_first_notification',
            field=models.BooleanField(default=False, help_text='First email — domestic US. Carrier-style shipment notification. Use instead of confirmation email.'),
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_at', models.DateTimeField(help_text='Exact UTC datetime to execute this action. Set precisely — cron checks every 5 minutes.')),
                ('stage_key', models.CharField(blank=True, choices=[('', 'No Stage Change'), ('label_created', 'Label Created'), ('package_received', 'Package Received'), ('departed_origin', 'Departed Origin Facility'), ('arrived_us_gateway', 'Arrived at US International Gateway'), ('export_clearance', 'Export Clearance Completed'), ('departed_us', 'Departed US — In Flight'), ('in_transit_intl', 'In Transit — International Flight'), ('arrived_hub', 'Arrived at Regional Sorting Hub'), ('departed_hub', 'Departed Sorting Hub'), ('arrived_destination_country', 'Arrived at Destination Country'), ('customs_processing', 'Customs Processing'), ('held_customs', 'Held at Customs — Payment Required'), ('payment_received', 'Payment Received — Customs Released'), ('departed_customs', 'Departed Customs — En Route'), ('arrived_local', 'Arrived at Local Delivery Facility'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('arrived_sort_facility', 'D — Arrived at Sort Facility'), ('held_delivery', 'D — Delivery Exception'), ('payment_received_domestic', 'D — Redelivery Fee Confirmed'), ('redelivery_intl', 'I-OPT — Delivery Exception Intl'), ('redelivery_intl_confirmed', 'I-OPT — Redelivery Confirmed Intl')], default='', help_text='Stage to advance to. Uses AI pipeline with local fallback. Leave blank for email-only.', max_length=50)),
                ('email_type', models.CharField(blank=True, choices=[('', 'No Email'), ('intl_first_notification', 'Intl — First Shipment Notification'), ('us_first_notification', 'US — First Shipment Notification'), ('confirmation', 'Confirmation'), ('intl_tracking', 'Intl Tracking Update'), ('intl_arrived', 'Intl Arrived in Country'), ('customs_fee', 'Customs Fee'), ('customs_fee_reminder', 'Customs Fee Reminder'), ('customs_fee_final', 'Customs Fee Final Notice'), ('us_tracking', 'US Tracking Update'), ('us_fee', 'US Shipping Fee'), ('us_redelivery_reminder', 'US Redelivery Reminder'), ('intl_redelivery_reminder', 'Intl Redelivery Reminder'), ('status_update', 'Status Update')], default='', help_text='Email to send at this time. Leave blank for stage-only action.', max_length=50)),
                ('custom_event_description', models.TextField(blank=True, default='', help_text='Optional: override AI-generated event description shown on tracking page.')),
                ('notes', models.CharField(blank=True, default='', help_text='Internal notes. Auto-filled with error detail if action fails.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='api.shipment')),
            ],
            options={
                'verbose_name': 'Scheduled Action',
                'verbose_name_plural': 'Scheduled Actions',
                'ordering': ['execute_at'],
            },
        ),
    ]
