# Generated by Django 5.2.5 on 2026-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_shipment_send_intl_first_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milanioutreachlog',
            name='smtp_provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail (diana@milanicollabs.com)'), ('ionos', 'IONOS (diana@milani-cosmetics.com)'), ('resend', 'Resend'), ('sendgrid', 'SendGrid')], default='', help_text='Which sending account was used for this message.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milani_smtp_provider',
            field=models.CharField(choices=[('gmail', 'Gmail — diana@milanicollabs.com (Google Workspace)'), ('ionos', 'IONOS — diana@milani-cosmetics.com (milani-cosmetics.com)')], default='gmail', help_text='Active SMTP account for Milani outreach. Switch here to rotate sending domain.', max_length=20),
        ),
        migrations.AlterField(
            model_name='milanioutreachlog',
            name='sendgrid_message_id',
            field=models.CharField(blank=True, help_text='Unique message ID (provider-agnostic)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='milanioutreachlog',
            name='status',
            field=models.CharField(help_text='e.g., Sent, Failed, Opened, Clicked, Bounced', max_length=50),
        ),
    ]
