# Generated by Django 5.2.5 on 2026-09-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_milaniemailvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milaniemailvariant',
            name='body',
            field=models.TextField(help_text='Email body. Use {name} for creator name, {greeting} for greeting. Separate paragraphs with a blank line. No em dashes.'),
        ),
        migrations.AlterField(
            model_name='milaniemailvariant',
            name='name',
            field=models.CharField(help_text="Internal label only. e.g. 'Variant A Summer 2026'", max_length=100),
        ),
        migrations.AlterField(
            model_name='milanioutreachlog',
            name='smtp_provider',
            field=models.CharField(blank=True, choices=[('resend_cosmetics', 'Resend — diana@milani-cosmetics.com'), ('resend_collabs', 'Resend — diana@milanicollabs.com'), ('resend', 'Resend (legacy)'), ('sendgrid', 'SendGrid (legacy)'), ('gmail', 'Gmail (legacy)'), ('ionos', 'IONOS (legacy)'), ('test', 'Test Mode')], default='', help_text='Which sending account was used for this message.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='milani_smtp_provider',
            field=models.CharField(choices=[('resend_cosmetics', 'Resend — diana@milani-cosmetics.com'), ('resend_collabs', 'Resend — diana@milanicollabs.com')], default='resend_cosmetics', help_text='Active Resend account for Milani outreach. Switch to rotate sending domain.', max_length=20),
        ),
    ]
