# Generated by Django 5.2.5 on 2026-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_milaniemailvariant_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilaniSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to permanently suppress from outreach.', max_length=254, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creator outreach suppression',
                'verbose_name_plural': 'Creator outreach suppressions',
            },
        ),
        migrations.AddField(
            model_name='creator',
            name='do_not_contact',
            field=models.BooleanField(default=False, help_text='Hard stop: suppress all creator outreach, including manual sends.'),
        ),
        migrations.AddField(
            model_name='creator',
            name='personalization_note',
            field=models.CharField(blank=True, default='', help_text='OPTIONAL: specific, genuinely observed creator detail. Leave blank to use a neutral message.', max_length=450),
        ),
        migrations.AddField(
            model_name='milaniemailvariant',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', help_text='New and legacy templates remain Draft until explicitly approved.', max_length=12),
        ),
        migrations.AddField(
            model_name='milaniemailvariant',
            name='campaign_name',
            field=models.CharField(blank=True, default='', help_text='Actual approved campaign name, not a historical label.', max_length=120),
        ),
        migrations.AddField(
            model_name='milaniemailvariant',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Last eligible date in Los Angeles local time; inclusive.', null=True),
        ),
        migrations.AddField(
            model_name='milaniemailvariant',
            name='is_evergreen',
            field=models.BooleanField(default=False, help_text='Only select for copy with no seasonal, date or unapproved promotional claims.'),
        ),
        migrations.AddField(
            model_name='milaniemailvariant',
            name='starts_on',
            field=models.DateField(blank=True, help_text='First eligible date in Los Angeles local time.', null=True),
        ),
        migrations.AddField(
            model_name='milanioutreachlog',
            name='body_snapshot',
            field=models.TextField(blank=True, default='', help_text='Exact sent body. Empty for historical records.'),
        ),
        migrations.AddField(
            model_name='milanioutreachlog',
            name='campaign_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='milanioutreachlog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='milaniemailvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active variants may be eligible for sending.'),
        ),
    ]
