# Generated by Django 5.2.5 on 2026-09-26 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_outreach_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilaniBatchSendGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilaniLaunchBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.milaniemailvariant')),
            ],
            options={
                'verbose_name': 'Manual Milani batch',
                'verbose_name_plural': 'Manual Milani batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilaniLaunchRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('blocked', 'Blocked'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('subject_snapshot', models.CharField(blank=True, max_length=255)),
                ('body_snapshot', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='api.milanilaunchbatch')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.creator')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'creator'), name='uniq_milani_batch_creator'), models.UniqueConstraint(fields=('batch', 'position'), name='uniq_milani_batch_position')],
            },
        ),
    ]
