# Generated by Django 5.2.5 on 2026-09-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_manual_batch_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='milanilaunchbatch',
            name='variant_revision_at',
            field=models.DateTimeField(blank=True, help_text='Exact campaign revision explicitly reviewed for unsent recipients.', null=True),
        ),
        migrations.AddField(
            model_name='milanilaunchrecipient',
            name='recipient_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
